version: '3'

volumes:
  fleetless_local_postgres_data: {}
  fleetless_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: fleetless_local_django
    container_name: fleetless_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8050:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: fleetless_production_postgres
    container_name: fleetless_local_postgres
    volumes:
      - fleetless_local_postgres_data:/var/lib/postgresql/data
      - fleetless_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: fleetless_local_docs
    container_name: fleetless_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./fleetless:/app/fleetless:z
    ports:
      - '9050:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8026:8025'
      - '1026:1025'

  redis:
    image: redis:6
    container_name: fleetless_local_redis

  celeryworker:
    <<: *django
    image: fleetless_local_celeryworker
    container_name: fleetless_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: fleetless_local_celerybeat
    container_name: fleetless_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: fleetless_local_flower
    container_name: fleetless_local_flower
    ports:
      - '5556:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: fleetless_local_node
    container_name: fleetless_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3050:3000'
